#!/usr/bin/env bash

rm -rf public/*
rm -rf spec/js/compiled/*
#find app markup style | grep -E '\.((js)|(glsl)|(css)|(html))$' | xargs touch
find app | grep -E '\.((js)|(glsl))$' | xargs touch

echo Cleaned up public/ and spec/js/compiled
